apiVersion: v1
kind: Pod
metadata:
  name: generator-runner-6
  labels:
    k8s-app: calogan
    calogan: generator
  namespace: uchicago-edu
spec:
  restartPolicy: Never
  containers:
    - name: ml   
      image: ivukotic/ml_platform_auto:latest
      args: ["/.run", "/ML_platform_tests/CaloGAN.sh", "sc2017_prp.py", "generator"]     
      resources: 
        limits: 
          alpha.kubernetes.io/nvidia-gpu: 1 # requesting 1 GPU          
          memory: "10Gi"
        requests:
          memory: "5Gi"
      volumeMounts:
      - name: nfs
        mountPath: /data/
        readOnly: false
      - name: nvidia-driver
        mountPath: /host-libs
        readOnly: true
      - name: calogan-store
        mountPath: /data-rook
  volumes:
  - name: nfs
    nfs:
      server: 67.58.53.150
      path: "/Data/PRCtutorial"
  - name: nvidia-driver
    hostPath:
      path: /var/lib/nvidia-docker/volumes/nvidia_driver/384.90/lib64
  - name: calogan-store
    flexVolume:
      driver: rook.io/rook
      fsType: ceph
      options:
        fsName: calogan-fs # name of the filesystem specified in the filesystem CRD.
        clusterName: rook # namespace where the Rook cluster is deployed
  nodeSelector:
    sc2017: da
