apiVersion: v1
kind: Pod
metadata:
  name: sleeper-runner
  labels:
    k8s-app: calogan
    calogan: sleeper
  namespace: uchicago-edu
spec:
  restartPolicy: Never
  containers:
    - name: ml   
      image: ivukotic/ml_platform_auto:latest
      args: ["sleep", "36500000"]
      volumeMounts:
      - name: calogan-store
        mountPath: /data-rook
  # nodeSelector:
  #   kubernetes.io/hostname: fiona8.calit2.uci.edu 
  #   #k8s-gpu-02.calit2.optiputer.net
  #   #fiona8.calit2.uci.edu 
  volumes:
  - name: calogan-store
    flexVolume:
      driver: rook.io/rook
      fsType: ceph
      options:
        fsName: calogan-fs # name of the filesystem specified in the filesystem CRD.
        clusterName: rook # namespace where the Rook cluster is deployed