apiVersion: v1
kind: Pod
metadata:
  name: transporter-runner-1
  labels:
    k8s-app: calogan
    calogan: transporter
  namespace: uchicago-edu
spec:
  restartPolicy: Never
  containers:
    - name: ml   
      image: ivukotic/ml_platform_auto:latest
      args: ["/.run", "/ML_platform_tests/CaloGAN.sh", "sc2017_prp.py", "transporter"]     
      resources: 
        limits:   
          memory: "2Gi"
        requests:
          memory: "1Gi"
      #args: ["sleep", "36500000"]
      volumeMounts:
      - name: calogan-store
        mountPath: /data-rook
  nodeSelector:
    kubernetes.io/hostname: k8s-gpu-01.calit2.optiputer.net
    #k8s-gpu-02.calit2.optiputer.net
    #fiona8.calit2.uci.edu 
  volumes:
  - name: calogan-store
    flexVolume:
      driver: rook.io/rook
      fsType: ceph
      options:
        fsName: calogan-fs # name of the filesystem specified in the filesystem CRD.
        clusterName: rook # namespace where the Rook cluster is deployed